### ISSUE TITLE
Page object returned by `ontargetcreated` not augmented with `openPortal`

### ISSUE THREAD

**Issue by 1nVitr0** [claabs/puppeteer-extra-plugin-portal#3]
When creating a `targetcreated` listener, e.g. to open a portal for all created tabs, the `Page` object returned by `target.page()` is not augmented with `openPortal`. I haven't investigated, this might be an issue of puppeteer-extra, if it is I will open another issue there.

```typescript
browser.on('targetcreated', async (target: Target) => {
  const page = await target.page();
  if (page) {
    const debugUrl = await page.openPortal(); // `openPortal` is not a function
    console.log(debugUrl);
  }
});
```

My workaround for now is calling the `openPortal` function of the plugin instance directly:

```typescript
const portalPlugin = puppeteer.plugins.find(
  (p) => p instanceof PuppeteerExtraPluginPortal,
) as PuppeteerExtraPluginPortal;

browser.on('targetcreated', async (target: Target) => {
  const page = await target.page();
  if (page) {
    const debugUrl = await portalPlugin.openPortal(page);
    console.log(debugUrl);
  }
});
```

**Comment by 1nVitr0** [comment]
Thanks for that :tada:

**Comment by rublev** [comment]
trying to understand, this doesn't handle tabs automatically?

**Comment by 1nVitr0** [comment]
@rublev The Portal is only active for the page on which `openPortal` was called on. If a new tab opens, you must call `openPortal` again on the new tab. I used the `targetcreated` event for that, which triggers for any new page or tab. Though I believe it also triggers for service workers, hence the `if (page)`.

**Comment by rublev** [comment]
> [@rublev](https://github.com/rublev) The Portal is only active for the page on which `openPortal` was called on. If a new tab opens, you must call `openPortal` again on the new tab. I used the `targetcreated` event for that, which triggers for any new page or tab. Though I believe it also triggers for service workers, hence the `if (page)`.

got it, thanks for the reply :)
